spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database: mysql
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      #mode: ALWAYS
      mode: NEVER
  devtools:
    restart:
      enabled: true
server:
  servlet:
    session:
      timeout: 1h
#logging:
#  level:
#    org:
#      hibernate:
#        stat: debug
#        type: trace
#        orm:
#          jdbc:
#            bind: trace