spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: true
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      #mode: ALWAYS
      mode: NEVER
  devtools:
    restart:
      enabled: true

